#!python
"""
VirtualBox CLI manager utility to streamline virtualbox features and actions
"""
## Import Libraries
### Built-in
import os
import sys
import lib.vbox as vbox_wrapper

def get_args():
    """
    Get command line arguments
    """

def setup():
    """
    General setup process
    """
    get_args()

def main():
    print("Hello World")
    vboxcli = vbox_wrapper.VirtualBox()
    vboxcli.list_vms()

if __name__ == "__main__":
    setup()
    main()

